#! /bin/bash
####-----------------------------Manual Deployment----------------------------

#ADD KEYS

wget -q -O- 'https://git.ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc' | sudo apt-key add -

#ADD REPO

apt-add-repository 'deb http://download.ceph.com/debian-infernalis/ trusty main'
apt-get update
#DOWNLOAD PACKAGES
wget -q http://download.ceph.com/debian-infernalis/pool/main/c/ceph/ceph_9.2.0-1trusty_amd64.deb

#Install PACKAGES

apt-get -yf install

apt-get install -y libaio1 libsnappy1 libcurl3 curl libgoogle-perftools4 libgoogle-perftools4 google-perftools libleveldb1

dpkg -i ceph_9.2.0-1trusty_amd64.deb

apt-get -yf install

apt-get install -y libaio1 libsnappy1 libcurl3 curl libgoogle-perftools4 libgoogle-perftools4 google-perftools libleveldb1

dpkg -i ceph_9.2.0-1trusty_amd64.deb

apt-get -yf install

apt-get install -y libaio1 libsnappy1 libcurl3 curl libgoogle-perftools4 libgoogle-perftools4 google-perftools libleveldb1

dpkg -i ceph_9.2.0-1trusty_amd64.deb

#Install Ceph

apt-get update && sudo apt-get install -y ceph qemu libvirt-bin

echo -e "\nPackage Installation is done\nProceed to next step:\n"
