#! /bin/bash
cd "$(dirname "$0")"


f_controller_groups()
{
controller_table=( $(grep "controller" ../sources/variables) )
c=0
while [ "$c" -lt "${#controller_table[@]}" ]
do
	
	echo "#Create Controller group
	define hostgroup {
        	hostgroup_name  controllers
                	alias           Controller Hosts
                	members         ${controller_table[@]}
        }
	


done




}









f_compute_groups()

{

}


#Create the Default all group for the hostgroups.cfg file

echo "# A simple wildcard hostgroup
define hostgroup {
	hostgroup_name  all
                alias           All Servers
                members         *
        }
" > /etc/nagios3/openstack/hostgroups.cfg
