#! /bin/bash

source sources/export_file
###---We start the installation script first
bash sources/ceph_hammer_packages

###########################----------------------------------ARRAY-----------------------------------------##############################

ip_addr="$(ifconfig eth1 | grep 'inet addr' | cut -d ':' -f 2 | cut -d ' ' -f 1)"

echo -e"\n[mon.$HOSTNAME]
host = $HOSTNAME
mon addr = $ip_addr:6789
mon data = /var/lib/ceph/mon/$cluster_name-$HOSTNAME
" >> /etc/"$cluster_name".conf

###create scp to send the .conf file to other servers ***********************************************



#################################################################################################################################

#Create the /var/lib/ceph/mon/cluster-node folder with also the upstart file
mkdir /var/lib/ceph/mon/$cluster_name-$HOSTNAME

ceph auth --cluster $cluster_name get mon. -o /tmp/ceph.mon.keyring

ceph mon --cluster $cluster_name getmap -o /tmp/monmap

##This function will allow us to add several '-i node' options
sudo ceph-mon --cluster $cluster_name -i $HOSTNAME --mkfs --monmap /tmp/monmap --keyring /tmp/ceph.mon.keyring


ceph-mon -i $HOSTNAME --cluster=$cluster_name

ceph mon add $HOSTNAME $ip_addr:6789

#RC LOCAL
sed_line=13
#upstart="sudo start ceph-mon "id=$HOSTNAME" "cluster=$cluster_name""
upstart="ceph-mon -i $HOSTNAME --cluster=$cluster_name"
sudo sed -i "$sed_line a $upstart" /etc/rc.local




####----------------------------------------------------Verification----------------------------###


read -p "We are now going to proceed with the verification. [Press any key]: " fake

echo -e "Verify that Ceph created the default pools"
ceph osd lspools

echo -e "\nVerify that the monitor is running"
ceph -s

#We run the SCP script
bash sources/ceph_scp



