#! /bin/bash


apt-get install -y pacemaker corosync fence-agents

corosync-keygen

#We need to send this key to the other servers
scp /etc/corosync/authkey compute@compute2:/etc/corosync/authkey   ###not root so we need to send this  to /tmp instead###


vim /etc/corosync/corosync.conf ##We change the bindnetaddr for the subnet  eg:10.0.0.0####

vim /etc/default/corosync    ##change from START=no to START=yes

service corosync start

service pacemaker start

update-rc.d pacemaker defaults

service pacemaker status

crm_mon --one-shot
