#! /bin/bash

cd "$(dirname "$0")"

source ../../../ceph_scripts/export_file

f_ceph_glance () 
{

apt-get install -y python-rbd

ceph --cluster $cluster_name auth get-or-create client.glance mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=images'
ceph --cluster $cluster_name auth get-or-create client.glance | tee /etc/ceph/${cluster_name}.client.glance.keyring

chown glance:glance /etc/ceph/${cluster_name}.client.glance.keyring

service glance-api restart
service glance-registry restart 

}
