#! /bin/bash

cd "$(dirname "$0")"

apt-get update && upgrade
apt-get install -y chrony

sed -i "s/server/#server/g" /etc/chrony/chrony.conf
echo "server controller iburst" >> /etc/chrony/chrony.conf

service chrony restart

chronyc sources

read -p "Verification for Chrony, press any key to continue:" fake1

