#! /bin/bash

cd "$(dirname "$0")"

source ../../0.General/pass_file

source ../../../ceph_scripts/export_file

source ../../0.General/openstack_functions

source ../../0.General/ceph_openstack_functions

#-----------------------------------------------Ceilometer DB with MongoDB-----------------------------------------

mongo --host controller --eval " \
  db = db.getSiblingDB("ceilometer"); \
  db.addUser({user: "ceilometer", \
  pwd: "${ceilometer_DBpass}", \
  roles: [ "readWrite", "dbAdmin" ]})"

#----------------------------------------------Ceilometer Configuration--------------------------------------------
source /root/admin-openrc.sh

#Create the ceilometer user:
openstack user create --domain default --password ${ceilometer_user_pass} ceilometer

#Add the admin role to the ceilometer user
openstack role add --project service --user ceilometer admin

#Create the ceilometer service entity

openstack service create --name ceilometer \
  --description "Telemetry" metering

#Create the Telemetry service API endpoints:
openstack endpoint create --region RegionOne \
  metering public http://controller:8777

openstack endpoint create --region RegionOne \
  metering internal http://controller:8777

openstack endpoint create --region RegionOne \
  metering admin http://controller:8777

#----------------------------------------Install and configuration Ceilometer--------------------------------------

apt-get install -y ceilometer-api ceilometer-collector \
  ceilometer-agent-central ceilometer-agent-notification \
  ceilometer-alarm-evaluator ceilometer-alarm-notifier \
  python-ceilometerclient


cp sources/ceilometer.conf /etc/ceilometer/ceilometer.conf
chown ceilometer.ceilometer /etc/ceilometer/ceilometer.conf

sed -i "s/CEILOMETER_DBPASS/${ceilometer_DBpass}/g" /etc/ceilometer/ceilometer.conf
sed -i "s/RABBIT_PASS/${rabbit_pass}/g" /etc/ceilometer/ceilometer.conf
sed -i "s/CEILOMETER_PASS/${ceilometer_user_pass}/g" /etc/ceilometer/ceilometer.conf

service ceilometer-agent-central restart
service ceilometer-agent-notification restart
service ceilometer-api restart
service ceilometer-collector restart
service ceilometer-alarm-evaluator restart
service ceilometer-alarm-notifier restart


echo -e "\nFirst step of Ceilometer installation is done\nWe now proceed with the Glance configuration\n"

#--------------------------------------Ceilometer for Glance--------------------------------------




























