#! /bin/bash

cd "$(dirname "$0")"

source ../../ceph_scripts/export_file

f_ceph_glance() 
{

apt-get install -y python-rbd

ceph --cluster $cluster_name auth get-or-create client.glance mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=images'
ceph --cluster $cluster_name auth get-or-create client.glance | tee /etc/ceph/${cluster_name}.client.glance.keyring

chown glance:glance /etc/ceph/${cluster_name}.client.glance.keyring

service glance-api restart
service glance-registry restart 

}


f_ceph_nova()
{

apt-get install -y ceph-common

ceph auth get-or-create client.cinder mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rx pool=images'

ceph auth get-or-create client.cinder | tee /etc/ceph/${cluster_name}.client.cinder.keyring
chown cinder:cinder /etc/ceph/${cluster_name}.client.cinder.keyring

ceph auth get-key client.cinder | tee client.cinder.key

nova_uuidgen=$(uuidgen)

cat > secret.xml <<EOF
<secret ephemeral='no' private='no'>
  <uuid>${nova_uuidgen}</uuid>
  <usage type='ceph'>
    <name>client.cinder secret</name>
  </usage>
</secret>
EOF

virsh secret-define --file secret.xml

virsh secret-set-value --secret ${nova_uuidgen} --base64 $(cat client.cinder.key) && rm client.cinder.key secret.xml

}

