#! /bin/bash

cd "$(dirname "$0")"

source pass_file

cp sources/mongodb.conf /etc/mongodb.conf
chown root.root /etc/mongodb.conf


apt-get install -y mongodb-server mongodb-clients python-pymongo

sed -i "s/BIND_IP/${controller_ip}/g" /etc/mongodb.conf

service mongodb stop
rm /var/lib/mongodb/journal/prealloc.*
service mongodb start
