#! /bin/bash

cd "$(dirname "$0")"

source pass_file

apt-get -y install mariadb-server python-pymysql

cp sources/mysqld_openstack.cnf /etc/mysql/conf.d/mysqld_openstack.cnf
chown root.root /etc/mysql/conf.d/mysqld_openstack.cnf


sed -i "s/BIND_ADDRESS/$controller_ip/g" /etc/mysql/conf.d/mysqld_openstack.cnf

service mysql restart


mysql_secure_installation

echo -e "\nMaria DB Installed\n"

