#! /bin/bash


cd "$(dirname "$0")"

apt-get update && apt-get upgrade -y

apt-get install software-properties-common
add-apt-repository cloud-archive:liberty
apt-get update && apt-get dist-upgrade
apt-get install python-openstackclient

reboot

