#! /bin/bash


cd "$(dirname "$0")"

apt-get update && apt-get upgrade -y

apt-get install -y software-properties-common
add-apt-repository cloud-archive:liberty
apt-get update && apt-get dist-upgrade -y
apt-get install -y python-openstackclient

reboot

