#! /bin/bash


cd "$(dirname "$0")"

#-----------------------------------------Functions to be incorporated inside our OpenStack Installation Scripts--------------------------------------------
source pass_file
#**************
#For futur modifications, we actually  
##***********

### MySQL function: we use it in every script were we would need to create a MySQL databse for an OpenStack service: keystone, glance, nova, etc
f_mysql()
{

# $1 will be the database name ex: keystone, glance, nova
# $2 will be the password value returned by "$(openssl rand -hex 10)" in the script

#EX:	f_mysql keystone password123

#We upper the $1 for the DBPASS
#local db_name="${1^^}_DBPASS"
#We create the password name to be added in the "pass_file" for export purposes
#local pass_name="${1}_DBpass"

###We add the password to the ../../0.General/pass_file
#echo -e "#$db_name:\nexport $pass_name=$2 \n" >> ../../0.General/pass_file


Q1="CREATE DATABASE $1;"
Q2="GRANT ALL PRIVILEGES ON $1.* TO '$1'@'localhost' \
  IDENTIFIED BY '$2';"
Q3="GRANT ALL PRIVILEGES ON $1.* TO '$1'@'%' \
  IDENTIFIED BY '$2';"
SQL="${Q1}${Q2}${Q3}"



mysql -uroot -p"$mysql_pass" -e "DROP DATABASE $1;"     ###TO BE REMOVED AFTER TESTING THE CODE#####
mysql -uroot -p"$mysql_pass" -e "$SQL"

echo -e "\n$1 Database Configured\n"

}

