#! /bin/bash


cd "$(dirname "$0")"

apt-get install -y rabbitmq-server

rabbitmqctl add_user openstack ${rabbit_pass}

rabbitmqctl set_permissions openstack ".*" ".*" ".*"

echo -e "\nRabbit MQ Installed\n"

